services:
  postgres:
    image: postgres:16-alpine
    container_name: vol_man_system_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vol_man_system
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vol_man_system"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
